export const styles = {
  app: {
    minHeight: "100vh",
    background: "#12121A",
    color: "#F2EFEA",
    fontFamily: "'Space Grotesk', sans-serif",
  },
  header: { padding: "28px 20px 0", borderBottom: "1px solid #232230" },
  headerInner: {
    maxWidth: 960,
    margin: "0 auto",
    display: "flex",
    justifyContent: "space-between",
    alignItems: "flex-start",
  },
  logoRow: { display: "flex", alignItems: "center", gap: 10 },
  logo: {
    fontFamily: "'Bebas Neue', sans-serif",
    fontSize: 34,
    letterSpacing: "0.08em",
    margin: 0,
    color: "#F2EFEA",
  },
  tagline: { margin: "2px 0 18px", color: "#8A8798", fontSize: 13.5 },
  marqueeLine: { height: 3, background: "linear-gradient(90deg, #E8A33D, #4FB3A9, transparent)" },
  main: { maxWidth: 960, margin: "0 auto", padding: "22px 20px 60px" },
  tabs: { display: "flex", gap: 6, overflowX: "auto", paddingBottom: 4, marginBottom: 18 },
  tabBtn: {
    display: "flex",
    alignItems: "center",
    gap: 6,
    whiteSpace: "nowrap",
    background: "#1C1B24",
    border: "1px solid #2B2A38",
    color: "#B5B2C0",
    padding: "8px 14px",
    borderRadius: 999,
    fontSize: 13.5,
    fontWeight: 500,
    cursor: "pointer",
    fontFamily: "inherit",
  },
  tabBtnActive: { background: "#E8A33D", borderColor: "#E8A33D", color: "#12121A", fontWeight: 600 },
  tabCount: { background: "rgba(255,255,255,0.12)", borderRadius: 999, fontSize: 11, padding: "1px 6px", marginLeft: 2 },
  toolbar: { display: "flex", gap: 10, marginBottom: 18, flexWrap: "wrap" },
  searchWrap: {
    display: "flex",
    alignItems: "center",
    gap: 8,
    background: "#1C1B24",
    border: "1px solid #2B2A38",
    borderRadius: 10,
    padding: "9px 12px",
    flex: 1,
    minWidth: 180,
  },
  searchInput: { background: "none", border: "none", outline: "none", color: "#F2EFEA", fontSize: 14, width: "100%", fontFamily: "inherit" },
  addBtn: {
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    gap: 6,
    background: "#E8A33D",
    color: "#12121A",
    border: "none",
    borderRadius: 10,
    padding: "9px 16px",
    fontSize: 14,
    fontWeight: 600,
    cursor: "pointer",
    fontFamily: "inherit",
  },
  linkBtn: { background: "none", border: "none", color: "#4FB3A9", fontSize: 13, cursor: "pointer", fontFamily: "inherit", padding: 4 },
  grid: { display: "grid", gridTemplateColumns: "repeat(auto-fill, minmax(260px, 1fr))", gap: 14 },
  card: {
    position: "relative",
    background: "#1C1B24",
    border: "1px solid #2B2A38",
    borderRadius: 12,
    padding: "16px 16px 14px",
    display: "flex",
    flexDirection: "column",
    gap: 10,
  },
  cardTear: { position: "absolute", top: 0, left: 20, width: 26, height: 8, background: "#12121A", borderBottomLeftRadius: 8, borderBottomRightRadius: 8 },
  cardTop: { display: "flex", gap: 12 },
  poster: { width: 48, height: 48, borderRadius: 8, display: "flex", alignItems: "center", justifyContent: "center", position: "relative", flexShrink: 0, overflow: "hidden" },
  posterImg: { position: "absolute", inset: 0, width: "100%", height: "100%", objectFit: "cover" },
  posterInitials: { fontFamily: "'Bebas Neue', sans-serif", fontSize: 17, color: "#12121A" },
  posterTypeIcon: { position: "absolute", bottom: -4, right: -4, background: "#12121A", borderRadius: 4, padding: 2, color: "#F2EFEA" },
  cardHeadInfo: { display: "flex", flexDirection: "column", gap: 3, minWidth: 0 },
  cardTitle: { margin: 0, fontSize: 15.5, fontWeight: 600, color: "#F2EFEA", lineHeight: 1.25 },
  genreTag: { fontSize: 11, color: "#4FB3A9", fontWeight: 500 },
  progressText: { margin: 0, fontSize: 12, color: "#8A8798" },
  notes: { margin: 0, fontSize: 13, color: "#B5B2C0", lineHeight: 1.4 },
  cardFooter: { display: "flex", justifyContent: "space-between", alignItems: "center", marginTop: "auto", paddingTop: 6 },
  cardActions: { display: "flex", gap: 4 },
  iconBtn: { background: "none", border: "none", color: "#8A8798", cursor: "pointer", padding: 5, borderRadius: 6, display: "flex" },
  empty: { display: "flex", flexDirection: "column", alignItems: "center", gap: 14, padding: "60px 20px", color: "#8A8798", textAlign: "center" },
  emptyText: { fontSize: 14, maxWidth: 320 },
  overlay: { position: "fixed", inset: 0, background: "rgba(0,0,0,0.6)", display: "flex", alignItems: "center", justifyContent: "center", padding: 20, zIndex: 50 },
  formCard: {
    background: "#1C1B24",
    border: "1px solid #2B2A38",
    borderRadius: 14,
    padding: 22,
    width: "100%",
    maxWidth: 420,
    maxHeight: "88vh",
    overflowY: "auto",
    display: "flex",
    flexDirection: "column",
    gap: 14,
  },
  formHeader: { display: "flex", justifyContent: "space-between", alignItems: "center" },
  formTitle: { margin: 0, fontFamily: "'Bebas Neue', sans-serif", fontSize: 24, letterSpacing: "0.03em" },
  label: { display: "flex", flexDirection: "column", gap: 5, fontSize: 12.5, color: "#B5B2C0", flex: 1 },
  input: { background: "#12121A", border: "1px solid #2B2A38", borderRadius: 8, padding: "9px 10px", color: "#F2EFEA", fontSize: 14, fontFamily: "inherit", outline: "none" },
  row: { display: "flex", gap: 10 },
  formActions: { display: "flex", justifyContent: "flex-end", gap: 10, marginTop: 6 },
  cancelBtn: { background: "none", border: "1px solid #2B2A38", color: "#B5B2C0", borderRadius: 10, padding: "9px 16px", fontSize: 14, cursor: "pointer", fontFamily: "inherit" },

  // --- auth / loading / error states (new) ---
  authWrap: { minHeight: "100vh", display: "flex", alignItems: "center", justifyContent: "center", padding: 20, background: "#12121A" },
  errorText: { color: "#F2B5B5", fontSize: 13, margin: 0 },
  noticeText: { color: "#4FB3A9", fontSize: 13, margin: 0 },
  loadingWrap: { display: "flex", flexDirection: "column", alignItems: "center", gap: 12, padding: "60px 20px", color: "#8A8798" },
  spinner: {
    width: 22,
    height: 22,
    border: "2.5px solid #2B2A38",
    borderTopColor: "#E8A33D",
    borderRadius: "50%",
    animation: "memoraSpin 0.7s linear infinite",
  },
  errorBanner: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    gap: 12,
    background: "#3A2222",
    color: "#F2B5B5",
    border: "1px solid #5A3232",
    borderRadius: 10,
    padding: "10px 14px",
    fontSize: 13,
    marginBottom: 16,
  },
  retryBtn: { background: "none", border: "1px solid #5A3232", color: "#F2B5B5", borderRadius: 8, padding: "5px 10px", fontSize: 12.5, cursor: "pointer", fontFamily: "inherit" },

  // --- Add-form mode toggle + global (TMDB) search tab ---
  modeToggle: { display: "flex", gap: 6, background: "#12121A", border: "1px solid #2B2A38", borderRadius: 10, padding: 4, marginBottom: 2 },
  modeToggleBtn: { flex: 1, background: "none", border: "none", color: "#8A8798", fontSize: 12.5, fontWeight: 600, padding: "7px 0", borderRadius: 7, cursor: "pointer", fontFamily: "inherit" },
  modeToggleBtnActive: { background: "#E8A33D", color: "#12121A" },
  searchHintText: { margin: 0, fontSize: 13, color: "#8A8798", textAlign: "left", lineHeight: 1.4 },
  searchResultsList: { display: "flex", flexDirection: "column", gap: 8, maxHeight: 320, overflowY: "auto" },
  searchResultRow: { display: "flex", alignItems: "center", gap: 10, background: "#12121A", border: "1px solid #2B2A38", borderRadius: 10, padding: "8px 10px" },
  searchResultPoster: { width: 36, height: 52, borderRadius: 6, flexShrink: 0, objectFit: "cover" },
  searchResultInitials: { fontFamily: "'Bebas Neue', sans-serif", fontSize: 13, color: "#12121A" },
  searchResultInfo: { flex: 1, minWidth: 0 },
  searchResultTitle: { margin: 0, fontSize: 13.5, fontWeight: 600, color: "#F2EFEA", whiteSpace: "nowrap", overflow: "hidden", textOverflow: "ellipsis" },
  searchResultMeta: { margin: "2px 0 0", fontSize: 11.5, color: "#8A8798", display: "flex", alignItems: "center", gap: 4 },
  searchResultAddBtn: { flexShrink: 0, background: "#E8A33D", color: "#12121A", border: "none", borderRadius: 8, padding: "7px 9px", cursor: "pointer", display: "flex", alignItems: "center", justifyContent: "center" },

  // --- Title Details modal ---
  detailsCard: {
    background: "#1C1B24",
    border: "1px solid #2B2A38",
    borderRadius: 14,
    width: "100%",
    maxWidth: 480,
    maxHeight: "90vh",
    overflow: "hidden",
    display: "flex",
    flexDirection: "column",
  },
  detailsBackdropWrap: { position: "relative", width: "100%", height: 160, flexShrink: 0, background: "#12121A" },
  detailsBackdropImg: { width: "100%", height: "100%", objectFit: "cover", display: "block" },
  detailsBackdropFallback: { width: "100%", height: "100%", display: "flex", alignItems: "center", justifyContent: "center" },
  detailsBackdropGradient: {
    position: "absolute",
    inset: 0,
    background: "linear-gradient(180deg, rgba(18,18,26,0) 40%, #1C1B24 100%)",
  },
  detailsCloseBtn: {
    position: "absolute",
    top: 10,
    right: 10,
    background: "rgba(18,18,26,0.7)",
    border: "1px solid rgba(255,255,255,0.15)",
    color: "#F2EFEA",
    borderRadius: 999,
    padding: 6,
    cursor: "pointer",
    display: "flex",
  },
  detailsPosterWrap: {
    position: "absolute",
    left: 20,
    bottom: -28,
    width: 64,
    height: 92,
    borderRadius: 8,
    overflow: "hidden",
    border: "3px solid #1C1B24",
    boxShadow: "0 4px 12px rgba(0,0,0,0.4)",
  },
  detailsPoster: { width: "100%", height: "100%", objectFit: "cover", display: "block" },
  detailsPosterFallback: { width: "100%", height: "100%", display: "flex", alignItems: "center", justifyContent: "center" },
  detailsScrollBody: { padding: "40px 20px 20px", overflowY: "auto", display: "flex", flexDirection: "column", gap: 14 },
  detailsTitle: { margin: 0, fontFamily: "'Bebas Neue', sans-serif", fontSize: 24, letterSpacing: "0.02em", color: "#F2EFEA" },
  detailsMetaRow: { display: "flex", flexWrap: "wrap", alignItems: "center", gap: 8 },
  detailsBadge: {
    display: "flex",
    alignItems: "center",
    gap: 4,
    fontSize: 12,
    color: "#B5B2C0",
    background: "#12121A",
    border: "1px solid #2B2A38",
    borderRadius: 999,
    padding: "3px 9px",
  },
  detailsOverviewText: { margin: 0, fontSize: 13.5, color: "#B5B2C0", lineHeight: 1.5 },
  detailsSectionTitle: {
    margin: "4px 0 -4px",
    fontSize: 11.5,
    fontWeight: 600,
    color: "#8A8798",
    textTransform: "uppercase",
    letterSpacing: "0.06em",
  },

  // --- Continue Watching row ---
  continueWrap: { marginBottom: 22 },
  continueHeading: {
    margin: "0 0 10px",
    fontFamily: "'Bebas Neue', sans-serif",
    fontSize: 18,
    letterSpacing: "0.04em",
    color: "#F2EFEA",
  },
  continueRow: { display: "flex", gap: 12, overflowX: "auto", paddingBottom: 4 },
  continueCard: {
    flexShrink: 0,
    width: 118,
    background: "none",
    border: "none",
    padding: 0,
    textAlign: "left",
    cursor: "pointer",
    fontFamily: "inherit",
    display: "flex",
    flexDirection: "column",
    gap: 6,
    borderRadius: 10,
  },
  continuePoster: {
    width: 118,
    height: 170,
    borderRadius: 10,
    position: "relative",
    overflow: "hidden",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    border: "1px solid #2B2A38",
  },
  continuePosterImg: { position: "absolute", inset: 0, width: "100%", height: "100%", objectFit: "cover" },
  continuePosterInitials: { fontFamily: "'Bebas Neue', sans-serif", fontSize: 26, color: "#12121A" },
  continuePosterIcon: { position: "absolute", bottom: 6, right: 6, background: "rgba(18,18,26,0.75)", borderRadius: 5, padding: 3, color: "#F2EFEA" },
  continueTitle: { margin: 0, fontSize: 12.5, fontWeight: 600, color: "#F2EFEA", whiteSpace: "nowrap", overflow: "hidden", textOverflow: "ellipsis" },
  continueMeta: { margin: 0, fontSize: 11, color: "#8A8798" },
  continueProgressTrack: { height: 3, borderRadius: 999, background: "#2B2A38", overflow: "hidden" },
  continueProgressFill: { height: "100%", background: "#E8A33D", borderRadius: 999 },

  // --- Stats / "Entertainment Passport" ---
  passportWrap: { display: "flex", flexDirection: "column", gap: 18 },
  passportCard: {
    position: "relative",
    overflow: "hidden",
    background: "linear-gradient(135deg, #23212E 0%, #1C1B24 55%, #17161F 100%)",
    border: "1px solid #2B2A38",
    borderRadius: 16,
    padding: "22px 22px 20px",
  },
  passportTopRow: { display: "flex", justifyContent: "space-between", alignItems: "flex-start" },
  passportEyebrow: {
    margin: 0,
    fontSize: 11,
    fontWeight: 600,
    color: "#4FB3A9",
    textTransform: "uppercase",
    letterSpacing: "0.14em",
  },
  passportStamp: {
    width: 46,
    height: 46,
    borderRadius: "50%",
    border: "1.5px dashed rgba(232,163,61,0.5)",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    transform: "rotate(-8deg)",
    flexShrink: 0,
  },
  passportHeadlineRow: { display: "flex", alignItems: "baseline", gap: 10, marginTop: 14 },
  passportHeadline: { fontFamily: "'Bebas Neue', sans-serif", fontSize: 52, lineHeight: 1, color: "#F2EFEA", letterSpacing: "0.01em" },
  passportHeadlineLabel: { fontSize: 13.5, color: "#B5B2C0" },
  passportMetaRow: { marginTop: 10, fontSize: 12, color: "#8A8798" },
  passportDivider: { borderTop: "1.5px dashed #33313F", margin: "18px 0 0" },

  statsGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fit, minmax(140px, 1fr))",
    gap: 12,
  },
  statCard: {
    background: "#1C1B24",
    border: "1px solid #2B2A38",
    borderRadius: 12,
    padding: "16px 15px",
    display: "flex",
    flexDirection: "column",
    gap: 4,
  },
  statCardIconRow: { display: "flex", alignItems: "center", justifyContent: "space-between" },
  statValue: { fontFamily: "'Bebas Neue', sans-serif", fontSize: 28, color: "#E8A33D", letterSpacing: "0.02em" },
  statLabel: { fontSize: 12, color: "#8A8798" },

  insightsCard: {
    background: "#1C1B24",
    border: "1px solid #2B2A38",
    borderRadius: 12,
    padding: "16px 18px",
    display: "flex",
    flexDirection: "column",
    gap: 14,
  },
  insightsTitle: {
    margin: 0,
    fontSize: 11.5,
    fontWeight: 600,
    color: "#8A8798",
    textTransform: "uppercase",
    letterSpacing: "0.08em",
  },
  splitLabelsRow: { display: "flex", justifyContent: "space-between", fontSize: 12, color: "#B5B2C0" },
  splitLabelDot: { display: "inline-block", width: 7, height: 7, borderRadius: "50%", marginRight: 5 },
  splitTrack: { display: "flex", height: 8, borderRadius: 999, overflow: "hidden", background: "#12121A" },
  insightRow: { display: "flex", alignItems: "flex-start", gap: 10 },
  insightIconWrap: {
    width: 28,
    height: 28,
    borderRadius: 8,
    background: "#12121A",
    border: "1px solid #2B2A38",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    flexShrink: 0,
    color: "#E8A33D",
  },
  insightText: { margin: 0, fontSize: 13, color: "#D8D5DF", lineHeight: 1.45 },
  passportEmpty: { textAlign: "center", padding: "8px 4px 2px", color: "#B5B2C0", fontSize: 13.5, lineHeight: 1.5 },

  // --- Shared "Home section" header (Continue Watching, Recently Added, Watchlist Preview) ---
  sectionHeadingRow: { display: "flex", alignItems: "baseline", justifyContent: "space-between", marginBottom: 10 },
  viewAllLink: { background: "none", border: "none", color: "#4FB3A9", fontSize: 12.5, fontWeight: 600, cursor: "pointer", fontFamily: "inherit", padding: 4 },
  homeGreeting: { margin: "0 0 4px", fontSize: 13.5, color: "#B5B2C0" },

  // --- Recent Activity ---
  activityList: { display: "flex", flexDirection: "column", gap: 12 },
  activityRow: { display: "flex", alignItems: "flex-start", gap: 10 },
  activityIconWrap: {
    width: 30,
    height: 30,
    borderRadius: "50%",
    background: "#1C1B24",
    border: "1px solid #2B2A38",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    flexShrink: 0,
  },
  activityText: { margin: 0, fontSize: 13, color: "#D8D5DF", lineHeight: 1.4 },
  activityTime: { margin: "2px 0 0", fontSize: 11, color: "#8A8798" },
  activityStars: { display: "inline-flex", gap: 1, verticalAlign: "middle", marginLeft: 2 },

  // --- Bottom Navigation ---
  bottomNavSpacer: { height: 78 },
  bottomNav: {
    position: "fixed",
    left: 0,
    right: 0,
    bottom: 0,
    zIndex: 40,
    background: "rgba(28,27,36,0.92)",
    backdropFilter: "blur(10px)",
    borderTop: "1px solid #2B2A38",
    display: "flex",
    justifyContent: "center",
    paddingBottom: "env(safe-area-inset-bottom, 0px)",
  },
  bottomNavInner: { display: "flex", width: "100%", maxWidth: 520 },
  bottomNavItem: {
    flex: 1,
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    gap: 3,
    padding: "10px 0 8px",
    background: "none",
    border: "none",
    color: "#8A8798",
    fontSize: 10.5,
    fontWeight: 500,
    cursor: "pointer",
    fontFamily: "inherit",
  },
  bottomNavItemActive: { color: "#E8A33D" },

  // --- Profile ---
  profileHeader: { display: "flex", flexDirection: "column", alignItems: "center", gap: 4, padding: "12px 0 22px", textAlign: "center" },
  profileAvatar: {
    width: 76,
    height: 76,
    borderRadius: "50%",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 6,
    border: "2px solid #2B2A38",
  },
  profileAvatarInitials: { fontFamily: "'Bebas Neue', sans-serif", fontSize: 28, color: "#12121A" },
  profileName: { margin: 0, fontFamily: "'Bebas Neue', sans-serif", fontSize: 24, letterSpacing: "0.02em", color: "#F2EFEA" },
  profileMeta: { margin: 0, fontSize: 12.5, color: "#8A8798" },

  // --- Settings ---
  settingsSection: { background: "#1C1B24", border: "1px solid #2B2A38", borderRadius: 12, overflow: "hidden", marginBottom: 16 },
  settingsSectionTitle: {
    margin: "0 0 8px 2px",
    fontSize: 11.5,
    fontWeight: 600,
    color: "#8A8798",
    textTransform: "uppercase",
    letterSpacing: "0.08em",
  },
  settingsRow: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 12,
    padding: "13px 16px",
    borderBottom: "1px solid #2B2A38",
  },
  settingsRowLast: { borderBottom: "none" },
  settingsRowLabel: { fontSize: 14, color: "#F2EFEA" },
  settingsRowValue: { fontSize: 12.5, color: "#8A8798" },
  settingsDangerBtn: {
    width: "100%",
    background: "none",
    border: "1px solid #5A3232",
    color: "#F2B5B5",
    borderRadius: 10,
    padding: "12px 16px",
    fontSize: 14,
    fontWeight: 600,
    cursor: "pointer",
    fontFamily: "inherit",
  },
  settingsAboutText: { margin: 0, fontSize: 12.5, color: "#8A8798", lineHeight: 1.5, padding: "2px 2px 4px" },

  // --- Search screen ---
  searchScreenInputWrap: { display: "flex", alignItems: "center", gap: 8, background: "#1C1B24", border: "1px solid #2B2A38", borderRadius: 10, padding: "11px 14px", marginBottom: 16 },
  searchScreenInput: { background: "none", border: "none", outline: "none", color: "#F2EFEA", fontSize: 15, width: "100%", fontFamily: "inherit" },
  recentSearchRow: { display: "flex", justifyContent: "space-between", alignItems: "center", marginBottom: 10 },
  recentSearchChips: { display: "flex", flexWrap: "wrap", gap: 8, marginBottom: 20 },
  recentSearchChip: {
    display: "inline-flex",
    alignItems: "center",
    gap: 6,
    background: "#1C1B24",
    border: "1px solid #2B2A38",
    borderRadius: 999,
    padding: "6px 12px",
    fontSize: 12.5,
    color: "#D8D5DF",
    cursor: "pointer",
    fontFamily: "inherit",
  },

  // --- Title Details screen (full page; the modal keeps its own tokens above) ---
  detailsScreenWrap: { margin: "-22px -20px 0", paddingBottom: 8 }, // bleed the hero to the main container's edges
  detailsScreenHero: { position: "relative", width: "100%", height: "min(38vw, 260px)", minHeight: 170, background: "#12121A" },
  detailsScreenHeroImg: { width: "100%", height: "100%", objectFit: "cover", display: "block", transition: "opacity 0.4s ease", position: "absolute", inset: 0 },
  detailsScreenHeroFallback: { position: "absolute", inset: 0 },
  detailsScreenHeroGradient: { position: "absolute", inset: 0, background: "linear-gradient(180deg, rgba(18,18,26,0.15) 30%, #12121A 100%)" },
  detailsScreenBackBtn: {
    position: "absolute",
    top: 14,
    left: 14,
    background: "rgba(18,18,26,0.72)",
    border: "1px solid rgba(255,255,255,0.15)",
    color: "#F2EFEA",
    borderRadius: 999,
    padding: 8,
    cursor: "pointer",
    display: "flex",
  },
  detailsScreenHeadRow: { display: "flex", alignItems: "flex-end", gap: 14, padding: "0 20px", marginTop: -44, position: "relative" },
  detailsScreenPoster: {
    width: 88,
    height: 128,
    borderRadius: 10,
    flexShrink: 0,
    border: "3px solid #1C1B24",
    boxShadow: "0 6px 16px rgba(0,0,0,0.45)",
  },
  detailsScreenHeadInfo: { minWidth: 0, paddingBottom: 4 },
  detailsScreenTitle: { margin: 0, fontFamily: "'Bebas Neue', sans-serif", fontSize: 30, lineHeight: 1.05, letterSpacing: "0.02em", color: "#F2EFEA" },
  detailsScreenOriginalTitle: { margin: "3px 0 0", fontSize: 12.5, color: "#8A8798", fontStyle: "italic" },
  detailsScreenActions: { display: "grid", gridTemplateColumns: "repeat(auto-fit, minmax(140px, 1fr))", gap: 8, padding: "0 20px", marginTop: 16 },
  detailsScreenActionBtn: {
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    gap: 7,
    background: "#1C1B24",
    border: "1px solid #2B2A38",
    color: "#D8D5DF",
    borderRadius: 10,
    padding: "11px 10px",
    fontSize: 13,
    fontWeight: 600,
    cursor: "pointer",
    fontFamily: "inherit",
  },
  detailsScreenActionBtnActive: { background: "#E8A33D", borderColor: "#E8A33D", color: "#12121A" },
  detailsScreenSection: { padding: "0 20px", marginTop: 20 },
};
